# Generated by Django 2.0.6 on 2019-03-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCRUDApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagesalemodel',
            name='imageURL',
            field=models.CharField(default='', max_length=800),
        ),
    ]
